### ISSUE TITLE
Delete Old Emblem Status for Supporters feature

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#101]
https://github.com/dota2unofficial/overthrow2/search?q=EmblemEnabled&unscoped_q=EmblemEnabled

https://github.com/dota2unofficial/overthrow2/blob/master/game/scripts/vscripts/common/patreons.lua#L74-L88

https://github.com/dota2unofficial/overthrow2/search?q=patreon_toggle_boots&unscoped_q=patreon_toggle_boots, https://github.com/dota2unofficial/overthrow2/search?q=patreon_bonus_button&unscoped_q=patreon_bonus_button

"modifier_donator"

These are remnants of an old cosmetic system. We have long deleted the menu to activate and deactivate this cosmetic emblem, but some users are stuck with it on, for example, my account is stuck with the emblem around my hero. We should delete these parts so that the emblem is always off. Also toggle boots functions should be removed, supports always get the boots, they can no longer toggle it off.

**Comment by Sheodar** [comment]
fot 12v12 e4925c22216e046e5dbf71726261b0a5f658fa52

**Comment by Sheodar** [comment]
Outdated
