### ISSUE TITLE
Silencer stealing too much int

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#107]
Valve's update seems to be incorrectly working with our fix, and now hes stealing 4 int per kill, not 2.

**Comment by Sheodar** [comment]
Fixed tooltips in 08c766d7e74bedff336bce8bd4b1d9bc1a6ca1ba

**Comment by Sheodar** [comment]
Fixed values/tooltips. Now steal 2 by attacks and permanent 2 by kill (3 with talent)
