### ISSUE TITLE
Leaderboard Issues (v1)

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#136]
![image](https://user-images.githubusercontent.com/16277198/79824637-106e6180-83da-11ea-9bd0-1b5f092554f5.png)

- [ ] Sometimes names are not showing
![image](https://user-images.githubusercontent.com/16277198/79824662-1fedaa80-83da-11ea-9977-2269b01b38dd.png)

- [ ] Add and "?" information circle next to rating to explain how it works
![image](https://user-images.githubusercontent.com/16277198/79824689-3136b700-83da-11ea-820e-e3c54aaa9aed.png)

- [ ] It still doesn't show the individual players score. If there is no score for that player it should say something like TBD (to be determined), but I think everbody is 2000 by default so that shouldnt be problem.

**Comment by Sheodar** [comment]
Outdated. We already have new style.
