### ISSUE TITLE
Balance issues again

### ISSUE THREAD

**Issue by quantuumsnot** [arcadia-redux/12v12#147]
Showing directly a real example:

Match 12v12 no feeders or quitters
Radiant team with global ult heroes - Mirana, Silencer, Invoker, Prophet and AoE ulters - Enigma, Veno ... + Dazzle
Dire team - strs like Pudge, Svem, WK and some disablers
First decline in gold for Dire - Around 10th minute first big combo-ult from the Radiant leads to 15-14 result despite that Dire lead 8-14.
Second decline in gold and practically losing the game - 5-6 minutes lated the diff is two times, 39-20. One guy from Dire was kicked only that saying the truth (trying to quote his exact words):

### **Match history**
[pick phase]
"PICK AT LEAST ONE GLOBAL ULT hero OR GAME IS LOST"
**_team silence_**
[game phase]
"Target at least Mirana or their weakest globals or the game is lost"
**_mega team silence_**
[First team wipe]
Some cool guy with WK already saying soemthing like "No proper support from bottom"
_**Pudge spams dota laughs**_
[Second team wipe]
Some another guy with KoTL dies at Northern Post and says something like "No help at all"
_**WK still tries his best to save the remnants of the team**_
Another Dire player with Sven or PA says something to WK "They even don't watch their minimaps" and something to others "If you don't do it at least listen to our signals and DON'T GO THERE TO DIE"
_Game chat spammed with a 2-3 lines of **Get back!**_
_**Team wiped again**_
[1 minute after the second team wipe]
The Dire player (Sven or PA) was kicked for hateful speech ...

My reaction to the current balance of the mod:
![meme make me cry](https://i.kym-cdn.com/photos/images/original/000/782/157/480.png)

Suggestion - disable all global ult heroes or at least increase CD of their ULTS:
Mirana - increase CD and decrease invisibility time
Silencer - increase CD and decrease silenced time
Invoker - lower the sunbeam's damage
Zeus - it's ok
Spectre - increase CD and lower the dispersion
Treant - at some moment whole map is eyed so it's good to lower their trigger radius for Overgrowth
Crystal - her arcane aura is passive so it's ok

**Comment by darklordabc** [comment]
This is very hard to balance heros. Players play custom games because they want to play with the original dota 2 heros, once we start changing from default, it upsets a lot of players, I know from experience.

**Comment by AustraliaIsMyCity** [comment]
have you tried getting good? @quantuumsnot

**Comment by Draze22** [comment]
Wait he thinks Zeus is fine but other heroes aren't?

**Comment by AustraliaIsMyCity** [comment]
Lmao

**Comment by quantuumsnot** [comment]
> have you tried getting good? @quantuumsnot

Yeah, stopped playing Dota and started to live again
