### ISSUE TITLE
Please redo mmr sorting

### ISSUE THREAD

**Issue by Michael-JY-He** [arcadia-redux/12v12#165]
The mmr sorting code is unfair because the players are distributed based on the sum of team mmr, not the avg team mmr. And parties are distributed based on the sum not avg.
This will result in the imbalance distribution that the first picking team can always pick better player than the other. E.g if all player are solo, the first picking team always pick 1st, 3st, 5th ... players, the other team is always 2nd, 4th, 6th ....

I've also been in this case: my friend and I are both 2300, there is a party of 6 and another good solo player with 4300. Your algorithm picks the party of 6 and the 4300 mmr player on the same side, my friend and I on the other. This makes the game super boring and waste of time.

Please make the mmr sorting more fair.

**Comment by Sheodar** [comment]
> E.g if all player are solo, the first picking team always pick 1st, 3st, 5th ... players, the other team is always 2nd, 4th, 6th ....
MMR sort for first sort player by mmr (from the highest to the lowest) 
> I've also been in this case: my friend and I are both 2300, there is a party of 6 and another good solo player with 4300. 
For first - if u want play in party - just play in party
For second - system shuffle parties for first

If u understand code - u can just emulate this in sublime. If u don't want do it - i could create test simulation for u. But just check screenshorts in discord for this. It already has some examples:
![image](https://user-images.githubusercontent.com/23509297/102697741-cecfd800-4240-11eb-9e5d-acbcedd8ee31.png)

P.S. We tried use some other not super hard sorting methods - all was worse then current system.

**Comment by Michael-JY-He** [comment]
![image](https://user-images.githubusercontent.com/17324953/102713597-0c5b5200-428f-11eb-99fc-d9296fbe5b45.png)

This is the result I got from your algorithm. It matches the avg mmr you showed. The optimal result is on the right. 

Usually people use swapping to create balanced partitions. 

e.g. after creating the initial partition, you can try swapping the highest mmr in the higher team, with the lowest mmr in the lower team.  Before actually swapping, precompute the new mmr difference after swapping. If new mmr difference is larger than the old, do not swap and try a next pair (either "2nd highest <-> lowest" or "highest <-> 2nd lowest" depending on which pair has a larger mmr difference). This will always converge to the optimal solution. 

BTW in my experience, when mmr difference is more than 200, it is always a stomp game which both sides do not enjoy at all.

**Comment by Sheodar** [comment]
I understand SOME logic can work in SOME situatuins. Example with 10000 mmr - unreal example. Did u rememver about party? I tried this algh, but it was worse when we took 1-3 parties in game (depends on mmr). But we should found compromise. It should work for solo players and for teams.  Don't forgot we should have same parties count in teams (no situation when we have 2 parties in first team and no parties in second team)

**Comment by Michael-JY-He** [comment]
I don't think party matters that much and we should have the same party counts on both side. What actually affect the game experience is the players' skill. 

What I mean is, the party should be distributed based on their avg mmr not the sum of their mmr. I've seen too many games that two 1000+ player party are on the weaker team and it makes the game even more super imbalanced.

Can you give me an example why the swapping logic does not work?

**Comment by Sheodar** [comment]
`I don't think party matters that much` - not true. A lot of games have 2 and more parties. It can be 2 player , but it can be 4+ players.
`party should be distributed based on their avg mmr not the sum of their mmr.` - i rememver joke in this moment, will interpret this. The first player have 7000 mmr, second player have 0 mmr. In average they have 3500 mmr.  
`I've seen too many games that two 1000+ player party are on the weaker team` - more teamplay - it's already powerfull bonus for players. Sorry, i canntot describe it clearly in eng. When u play with party - it's more teamplay, coordination, communication.
`Can you give me an example why the swapping logic does not work?` - parties

**Comment by Michael-JY-He** [comment]
You must have not played 12v12 much. No matter a player is in party or not, their mmr will converge to their skill. If they play in a party, their mmr will rise and converge to the mmr which already count the teamplay, coordination, communication inside. 

I don't know why the avg 3500 for a 7000 + 0 is a problem? What you try to do is to balance the player skills. If players' mmr is true (shows their true skills), then 3500 is appropriate for them. This 7000+0 party is the same as two 3500 players.

Give me a real example like the 10000 mmr example you gave me. I don't think the swapping fails.

**Comment by Sheodar** [comment]
And yeah, 1 more moment. Forgot about parties now. About swapping. Just rememver it's not only numbers. U suggest punish high mmr players. The 1st by mmr player will be in same team with the worst player. 
`I don't know why the avg 3500 for a 7000 + 0 is a problem?` - yes, because the presence of a 7k player in a team is more important than a 0k player.
`Give me a real example like the 10000 mmr example you gave me. I don't think the swapping fails.` - i need go for now (will back little later). I have some screensots from real game/emulations. Btw, u still say nothing about parties. 
If u can give me lua algh for your option - it could be cool (it should work with parties how i described it before). 
Btw, i don't like this logic little too, if your option will be better in some simulation test - cool

**Comment by Michael-JY-He** [comment]
I don't write in lua so I can't give you the code. 
If you understand swapping correctly, the 1st players is not necessarily to be in the same team as the last.
If 7k + 0k is their real mmr which shows their real skills, then they are the same as 3500 + 3500. Because if not, the 7k will keep rising to 8k, 9k, 10k until it reaches his correct skill. At that time, they are the same as 4000 + 4000 or 4500 + 4500. So that is their equal mmr.

> u still say nothing about parties
What do you want me to say? We've been talking about parties all the time right?

The biggest problem of using total mmr of a party is that, low mmr party is usually on the weak team. This makes the game too imbalanced. If they are noob, no matter how much teamplay, coordination, etc they have, it is hard for them to beat good players. 
e.g. (and this is not rare) 6 players: 3000, 2500, 2X2000, 2X1600. The two 1600 are in a party, Your algo will be 3000 + 2500 + 2000 and 2*1600 + 2000. This will be team 1 stomping team 2 within 15min. This is like the 3000+2500 good players bullying the 1600 party.

**Comment by Sheodar** [comment]
Hi i little imlement it. I got same results for 10000 example. But new example:
![image](https://user-images.githubusercontent.com/23509297/102817979-6a944c00-43d9-11eb-98a5-11fdd44259ec.png)
Your option and my option have same results (same players in same teams)
U can test it with this code: https://codeshare.io/5OjrkN
For any lua compiler online (just example: https://rextester.com/l/lua_online_compiler )

**Comment by Michael-JY-He** [comment]
Thank you for your quick followup!

This line 
if #partyData.players >= MinDiffPlayerCount and not partyData.sorted then

I don't know what MinDiffPlayerCount is for? But I simply change it to 0 by running SortTeam(0) and the code runs as I expect. The party 6 are with other low players. The two teams mmr are 2646 and 2131.

Think about the 900 party, if they are always on the opposite side of the party 6, they might keep losing to 0......That would be tragic.

**Comment by Sheodar** [comment]
It's part of code for sort teams > sort solo players order. Maybe it's not have sense for this algh, yes

**Comment by Michael-JY-He** [comment]
I think this new mmr sorting is good now. What do you think?
If there is still some problem that the new algo can't handle, probably swapping needs to to be added. But I think now this avg mmr soritng is good. 

One case might need to consider. If both teams already have 11 players. And the last two players to be assigned are in a party. If
MinDiffPlayerCount is removed, then it can't handle this case.

**Comment by Sheodar** [comment]
both teams cannot have 11 players in we have party with 2 people (for my first and second look). U can change player data for emulate different sitatuations. 
* same party id = same party

**Comment by Sheodar** [comment]
One of the example:
![image](https://user-images.githubusercontent.com/23509297/102844203-93393780-4413-11eb-953a-0237f82c6d0a.png)
But it's physically inpossible for any sort kekw (one party was destroyed)

**Comment by Michael-JY-He** [comment]
I see. There will not be 11:11. You are right.

**Comment by Michael-JY-He** [comment]
But I find a problem after emulation. Suppose all players are solo. After sorting, it would always be the 1st + 14th + 15th + ... + 24th in one team and 2nd + 3rd + ... + 13th in the other team.
Because after 1st and 2nd are distributed to two teams, 2nd is in the weaker team and it will keep adding the next player until full.

This is not good I think.

**Comment by Sheodar** [comment]
I little updated alghrotith. Can u test it again (with old players data just) ?

**Comment by Michael-JY-He** [comment]
Looks it is working on some cases. But I don't understand the line you changed:

`return (teams[_teamId].mmr - partyData.mmr) / (playersCount + #partyData.players)`

teams.mmr is the total mmr. partyData.mmr is the avg mmr of the party. What does this line mean?

**Comment by Michael-JY-He** [comment]
I think the old logic in this part is good. The team with low mmr sum should pick the next player.

**Comment by Sheodar** [comment]
Yeah, it's little magic, just i gave 7:36 AM now. I'll check it and I will think again

**Comment by Sheodar** [comment]
btw, if work only with avearage MMR it will get a problem. The 1st player will get the last worst 11 players. Because if 1st player have 4000 mmr, it will have 4000 mmr avg all time. If second and third player will have 3999 mmr they will have 3999 mmr and they need better player.

**Comment by Michael-JY-He** [comment]
> btw, if work only with avearage MMR it will get a problem. The 1st player will get the last worst 11 players. Because if 1st player have 4000 mmr, it will have 4000 mmr avg all time. If second and third player will have 3999 mmr they will have 3999 mmr and they need better player.

> But I find a problem after emulation. Suppose all players are solo. After sorting, it would always be the 1st + 14th + 15th + ... + 24th in one team and 2nd + 3rd + ... + 13th in the other team.
Because after 1st and 2nd are distributed to two teams, 2nd is in the weaker team and it will keep adding the next player until full.

We are saying the same thing.

**Comment by AustraliaIsMyCity** [comment]
Will work on this and submit PR probably in the next 10 days or so

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/132164030-505e8e85-879a-4726-91b5-e8045e1d5fca.png)

**Comment by AustraliaIsMyCity** [comment]
will fix this and #516 at the same time.
