### ISSUE TITLE
Vengful Spirit bug, needs confirming 

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#171]
![image](https://user-images.githubusercontent.com/16277198/103475172-fc9b4c00-4dfe-11eb-8d28-180f9b96653d.png)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/103475745-e93cb080-4dff-11eb-965e-b41be4c0c6e3.png)
Unable to replicate, died to roshan with aghs and bought branches while dead. Vengeful respawned at her illusion with said branches.
Also unable to replicate the quick buy bug.

**Comment by GeneralDotV2** [comment]
"Also unable to replicate the quick buy bug."
You need perks for the issue to be replicated fyi.. It has to do with shop insta buy that patreons get.
