### ISSUE TITLE
New Server works

### ISSUE THREAD

**Issue by SanctusAnimus** [arcadia-redux/12v12#178]
- [x] Patreon lib replacement
- [x] Renaming CHC related names to neutral (or 12v12/Overthrow separated)
- [x] Tweaking UI to remove CHC signs
- [x] Remove Barrage Collection tab and items from all treasures
- [x] Remove Rerolls from Collection
- [x] Update Collection items and treasure contents
- [x] MMR reconsideration
- [x] Glory/Exp/Levels reconsideration
- [x] Tweaking UI to match new Collection style
- [x] Exporting supporters from old server into new one **(RIGHT BEFORE MIGRATION)**
- [x] Remove debug prints
- [x] Replace timers lib with CHC one, add perf report to the after-match
- [x] Add quests / prices / dev keys
- [x] Fix payment landing page being CHC themed
Server only
- [x] Streaks, wins/loses, kda
- [x] roles and access correction for managed database instance
- [x] Disable unused stats pages (Items, Abilities, Masteries, Innates, Rounds)
- [x] Correct other pages
- [x] Correct raw queries

**Comment by darklordabc** [comment]
@Sheodar @fcalife

**Comment by SanctusAnimus** [comment]
Most works are done, specific would go into separate issues
