### ISSUE TITLE
Bring back Tome

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#197]
Make sure that gold bug is fixed.

**Comment by Sheodar** [comment]
What is problem? Just forgot this problem

**Comment by Sheodar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import fast delivery items from OT to 12v12 (it will fix bugs connected with it)](https://trello.com/c/ti20O2gl/224-import-fast-delivery-items-from-ot-to-12v12-it-will-fix-bugs-connected-with-it)

**Comment by Sheodar** [comment]
Imported fast items system from OT. Should fix some bugs from old system. https://github.com/dota2unofficial/12v12/commit/44e97eed40f86bc377604761269cb632355d66b6

**Comment by Sheodar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update fast items system in 12v12](https://trello.com/c/P0GHdMjc/251-update-fast-items-system-in-12v12)

**Comment by Sheodar** [comment]
Need checks after revert old system
