### ISSUE TITLE
Fix Minimap Issue with Dynamic Map Loading and reconnecting

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#204]
![image](https://user-images.githubusercontent.com/16277198/107141973-1f7dca80-6980-11eb-83a7-b3d615c055e6.png)

**Comment by darklordabc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mini map Issue](https://trello.com/c/Hx8B3mtc/274-mini-map-issue)

**Comment by SanctusAnimus** [comment]
Irrelevant
