### ISSUE TITLE
Muting a player does not mute the voice lines they play

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#224]
Very annoying

**Comment by Snoresville** [comment]
similar issue to #180

**Comment by Snoresville** [comment]
Did you mute the player through the scoreboard or through the item?

**Comment by darklordabc** [comment]
Score board but it shouldn't matter

**Comment by Snoresville** [comment]
actually, the method does matter, because the mute through item method doesn't seem to communicate back to server the mute state

**Comment by Sheodar** [comment]
Fixed 7ead988976ab887c36a8c9811c51f94d6768b18c
