### ISSUE TITLE
Add force disconnection for players at start of game

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#226]
There is a bug where players get a penalty after 5 minutes, to avoid this players need to disconnect and reconnect. To enforce this workaround, the game should force players to disconnect at start of game, it should pause for game for some time to allow players to reconnect.

**Comment by Snoresville** [comment]
testing this on my end

**Comment by Snoresville** [comment]
should be good to go, waiting for feedback

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/112955903-6cfc0400-9187-11eb-83a5-e5b09e865f8d.png)
