### ISSUE TITLE
Amplify Curse Perk does not exist

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#237]
![image](https://user-images.githubusercontent.com/16277198/116229319-b2691c80-a799-11eb-967d-20fb02a1fb53.png)
I tested it, clicking on it gives nothing. 

Please now double-check all the perks to make sure no other non-existent perks exist.

**Comment by Sheodar** [comment]
Fixed in `perks_new_and_ref` branch. Was error in regex tracking
