### ISSUE TITLE
Replace/Update some of the new perks

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#240]
1. Replace Little Traveler with Teleport (Global Teleport as Neutral Item) Exactly same graphics and speeds as NP ability. Cannot be shared with teammates.
Lvl 1 90. 
lvl 2 60. 
lvl 3 30

2. Delayed Damage cannot kill you by itself, the time delay for damage gets longer as you level it up

3. Basic Builder leave as it is

4. Magician leave as it is

5. Replace Basic Tinkerer with Linkens Pendant (Neutral Item). Cannot be shared with teammates.
60s cd, 400 cast range, 3s duration
45s cd, 550 cast range, 4s duration
30s cd, 700 cast range, 5s duration

6. Replace Hunter with Buffs Amplify - Opposite of Curses Amplify, but requies testing every ability sorry @Sheodar#3233

**Comment by fcalife** [comment]
For the delayed damage perk: make it 6/8/10s delay, 8/16/32% damage, and make the delayed damage nonlethal
