### ISSUE TITLE
Add Tipping

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/12v12#241]
Details in discord 
https://discord.com/channels/501306949434867713/704020241885167766/837545634180628500

**Comment by darklordabc** [comment]
@Sheodar

**Comment by darklordabc** [comment]
We should probably also add tipping to CHC and Overthrow

**Comment by AustraliaIsMyCity** [comment]
see #253

**Comment by Sheodar** [comment]
Implemented
