### ISSUE TITLE
Create icons for the newly added perks

### ISSUE THREAD

**Issue by fcalife** [arcadia-redux/12v12#242]
Perk descriptions:

1. Teleport: grants you a neutral item which allows teleporting (very similar mechanically to nature's prophet teleport).
2. Delayed Damage: part of the damage you take is delayed (similar mechanically to kunkka's rum effect).
3. Builder: periodically heals your lowest health tower.
4. Magician: increases your spells' area of effect.
5. Linken's Pendant: grants you a neutral item with an active identical to linken's sphere. Does not grant the passive linken's effect.
6. Buff Amplify: increases the duration of buffs you grant to yourself or your allies.

Here are the icons used for the current perks (49x49 PNGs, imported from Underlords):

![agi_for_kill](https://user-images.githubusercontent.com/7921728/116776086-33940e00-aa3d-11eb-88a3-310a099e6376.png)
![attack_range](https://user-images.githubusercontent.com/7921728/116776087-342ca480-aa3d-11eb-8d5b-1df2d71f2533.png)
![bonus_agi](https://user-images.githubusercontent.com/7921728/116776088-34c53b00-aa3d-11eb-952c-1c62b698d055.png)
![bonus_all_stats](https://user-images.githubusercontent.com/7921728/116776089-34c53b00-aa3d-11eb-975e-34be8cc2d45e.png)
![bonus_gold](https://user-images.githubusercontent.com/7921728/116776090-355dd180-aa3d-11eb-8215-70c551049820.png)
![bonus_hp_pct](https://user-images.githubusercontent.com/7921728/116776091-355dd180-aa3d-11eb-885c-d6d9e5412015.png)
![bonus_int](https://user-images.githubusercontent.com/7921728/116776093-355dd180-aa3d-11eb-9e6b-7765b5d3a18d.png)
![bonus_movespeed](https://user-images.githubusercontent.com/7921728/116776094-35f66800-aa3d-11eb-8ff4-3a8e2bad8988.png)
![bonus_str](https://user-images.githubusercontent.com/7921728/116776095-35f66800-aa3d-11eb-87b0-4e690034fabe.png)
![cast_range](https://user-images.githubusercontent.com/7921728/116776096-368efe80-aa3d-11eb-95b1-9fb355b5d7e1.png)
![cd_after_death](https://user-images.githubusercontent.com/7921728/116776097-368efe80-aa3d-11eb-9033-12a97cc34c94.png)
![cleave](https://user-images.githubusercontent.com/7921728/116776098-37279500-aa3d-11eb-8d74-c0b6cd6d9add.png)
![cooldown_reduction](https://user-images.githubusercontent.com/7921728/116776099-37279500-aa3d-11eb-9ea1-cd31072b2019.png)
![damage](https://user-images.githubusercontent.com/7921728/116776100-37279500-aa3d-11eb-8ba4-0ac2fec3d777.png)
![debuff_time](https://user-images.githubusercontent.com/7921728/116776101-37c02b80-aa3d-11eb-961c-a99a4bf5e843.png)
![evasion](https://user-images.githubusercontent.com/7921728/116776102-37c02b80-aa3d-11eb-82f2-90003531a08b.png)
![hp_regen](https://user-images.githubusercontent.com/7921728/116776103-3858c200-aa3d-11eb-9e6c-aff6740dd137.png)
![int_for_kill](https://user-images.githubusercontent.com/7921728/116776104-3858c200-aa3d-11eb-978a-3b4e044ba927.png)
![lifesteal](https://user-images.githubusercontent.com/7921728/116776105-3858c200-aa3d-11eb-8d28-3f80b053f7cd.png)
![mag_resist](https://user-images.githubusercontent.com/7921728/116776106-38f15880-aa3d-11eb-8f90-b8523b8951ac.png)
![manaburn](https://user-images.githubusercontent.com/7921728/116776109-38f15880-aa3d-11eb-9f8d-4add332d42ff.png)
![mp_regen](https://user-images.githubusercontent.com/7921728/116776110-3989ef00-aa3d-11eb-8481-74e33b1924fb.png)
![outcomming_heal_amplify](https://user-images.githubusercontent.com/7921728/116776111-3989ef00-aa3d-11eb-814a-b1be08810baf.png)
![spell_amp](https://user-images.githubusercontent.com/7921728/116776112-3a228580-aa3d-11eb-8bd7-11b77c05cf1d.png)
![spell_lifesteal](https://user-images.githubusercontent.com/7921728/116776113-3a228580-aa3d-11eb-9a68-07ac399cac49.png)
![status_resistance](https://user-images.githubusercontent.com/7921728/116776114-3abb1c00-aa3d-11eb-9757-8a0fdbff7c30.png)
![str_for_kill](https://user-images.githubusercontent.com/7921728/116776115-3abb1c00-aa3d-11eb-9aa7-edfabce915e9.png)

Here are the current icons for some of these abilities (you can keep some of them if you think they're good enough):

Builder
![builder](https://user-images.githubusercontent.com/7921728/116776171-63dbac80-aa3d-11eb-8229-dadde622da36.png)

Delayed damage
![delayed_damage](https://user-images.githubusercontent.com/7921728/116776175-69d18d80-aa3d-11eb-8b3e-27db3d9b5a9c.png)

Magician
![magician](https://user-images.githubusercontent.com/7921728/116776181-70f89b80-aa3d-11eb-891e-69e3642aa3fd.png)

And here are some currently unused icons:

![gpm](https://user-images.githubusercontent.com/7921728/116776186-7eae2100-aa3d-11eb-89e2-618b871dd52c.png)
![hunter](https://user-images.githubusercontent.com/7921728/116776187-7f46b780-aa3d-11eb-941d-902f75c759be.png)
![tinkerer](https://user-images.githubusercontent.com/7921728/116776189-7f46b780-aa3d-11eb-9c84-017ccf7318f3.png)
![traveler](https://user-images.githubusercontent.com/7921728/116776190-7fdf4e00-aa3d-11eb-9b2f-d73429f8f885.png)

**Comment by natoshi** [comment]
![image](https://user-images.githubusercontent.com/3074666/116783113-9913e900-aa95-11eb-9f06-580a496dfc6a.png)
