### ISSUE TITLE
Courier bug, going to middle

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#245]
many reports of courier going to centre on dire side instead of back to base

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/839058815042322472)

**Comment by fcalife** [comment]
The couriers don't go there, they SPAWN on the map's center (0,0 coordinate). When this happens, players cannot control their couriers.

Seems to only happen on dire side.

**Comment by GeneralDotV2** [comment]
Happens to Radiant players too
