### ISSUE TITLE
Huge lag during pick phase

### ISSUE THREAD

**Issue by quantuumsnot** [arcadia-redux/12v12#25]
After the ban phase ends the pick one starts where players ALWAYs face a huge lag - freeze screen with mouse cursor active and sometimes it's so worse that pick timer ended and players loose gold (for example last 20-30 games when this happened I started with around 580-585 gold). Suggested solution by most of the players is to remove 'not picking in time' gold penalty or fix the lag. It happens mostly on first 3 times dota is closed and loaded again. Adding '-map dota' to preload the map before actual game as launch option doesn't help

**Comment by quantuumsnot** [comment]
15 seconds ago went in the game with 562 gold ... 562

**Comment by Sheodar** [comment]
Should be outdated. We already have slowing for first 30 game seconds.
