### ISSUE TITLE
Mute does not stop spam laughter

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#252]
![Screenshot_20210508-172916_Discord](https://user-images.githubusercontent.com/16277198/117530895-05a55f80-b023-11eb-9a5f-033cf770ea1c.jpg)
it should

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/840490651266187315)

**Comment by Sheodar** [comment]
Should be fixed now after new scoreboard
