### ISSUE TITLE
Monkey King ult spawns monkeys in wrong spots and they don't atttack

### ISSUE THREAD

**Issue by GeneralDotV2** [arcadia-redux/12v12#255]
Now I have no idea what is causing the issue, but I do have a screenshot and video of it happening. This happened 3 out of the last 3 games I played as Monkey King.

 Here is a short video clip of it happening when I use the ult.
 https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/GeneralDotV2/ShareX/05-11-2021/bugged_monkey_king_ult.mp4

Here is a screenshot showing the monkeys spawning in a group / out of normal positions.
https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/GeneralDotV2/ShareX/05-15-2021/dota2_07-58PM.png

This happens everytime I ult, not just randomly.

**Comment by Draze22** [comment]
Pretty sure this has been fixed.
