### ISSUE TITLE
Review the kick troll feature to prevent abuse

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#261]
Players have often reported abuse of the kick troll item, claiming innocent players are kicked for performing poorly (in the eyes of the kickers), or for no reason at all, simply to make the game safe to leave.

The players who are 'abusing' it claim to be using it for legitimate reasons.

We need to either brainstorm a way to stop the 'abuse', or, if what's happening is intended, make it clear that it is so. AFAIR, the kick feature was meant only to prevent trolls and griefers.

Opened from Discord by **Firetoad#5132**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/845382708204535808)

**Comment by ArcadiaReduxAutomation** [comment]
<@232166462901583872>abc your opinion is required here

Comment from Discord by **Sanctus Animus#3413**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/845383277871104020)

**Comment by Draze22** [comment]
We also need to try and solve patreon supporters not being able to be kicked when they are trolling or griefing.

**Comment by AustraliaIsMyCity** [comment]
@darklordabc your input is needed https://discord.com/channels/501306949434867713/828460929427046430/857394180845600788

**Comment by Draze22** [comment]
We now have a planned solution to this: #319.
