### ISSUE TITLE
Track game winrates based on difference in MMR

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/12v12#262]
Grouped into ranges every 50 MMR difference

for example, if a game is won by a team with 1700 average MMR and the opposing team has 1825 average MMR, then add 1 win and 1 game to the +100-149 range, and 1 loss and 1 game to the -101-150 range

This will assist in adjusting the weak team buff, plus I'm just really interested to see the numbers

**Comment by SanctusAnimus** [comment]
Are you high on stats again

**Comment by SanctusAnimus** [comment]
Also
> I'm just really interested to see the numbers  

Not even close to being a reason to implement this

> assist in adjusting the weak team buff  
No reason to do that since we don't have any kind of calibration, mmr matchmaking etc. MMR here is just a number and means mostly nothing, since it's a CG. 

Discuss with @darklordabc and then if he for some ungodly reason approves, we'll think about it

**Comment by AustraliaIsMyCity** [comment]
boring

**Comment by AustraliaIsMyCity** [comment]
> No reason to do that since we don't have any kind of calibration, mmr matchmaking etc. MMR here is just a number and
but we do have mmr based matchmaking

**Comment by SanctusAnimus** [comment]
we don't? It's just a sorting inside a game, you aren't getting in a lobby where all players have "relatively" close skill level, or at least numbers. Even if you multiply income gold and exp for noob 5 times, he'll still lose, and overdoing it to something extreme (i. e. 10x boost, buffs etc) just entices to make smurfs and ruin games.
Not to mention that this is a serious balance change, you should've asked darklord before even opening this. And he wasn't exactly interested in your last change, was he? Don't try to sneak such things behind his back

**Comment by SanctusAnimus** [comment]
By the way, does current weak team buff even work? Considering #258 is a thing, how do you know it's not enough already?

**Comment by AustraliaIsMyCity** [comment]
yes, i just fixed it

**Comment by AustraliaIsMyCity** [comment]
i dont know if its enough already, it would be easier to know if we had stats but anyways im happy to just drop it
