### ISSUE TITLE
fix stylish on perks window

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#263]
probably for overthrow too
![image](https://cdn.discordapp.com/attachments/501306949434867715/845947402082189352/dota2_12-14AM.png)

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/845947402871242772)

**Comment by darklordabc** [comment]
@AnnHuangofNJUST @StariyOld

**Comment by ArcadiaReduxAutomation** [comment]
see?

Comment from Discord by **Sanctus Animus#3413**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/845949646903312395)

**Comment by Sheodar** [comment]
Fixed for 12v12/OT/CHC.
