### ISSUE TITLE
Meepo with Divided we stand leveled + aghs = Aegis ceases to function upon death of meepo

### ISSUE THREAD

**Issue by GeneralDotV2** [arcadia-redux/12v12#266]
I have tested this and found the exact cause in-game.
"Meepo with Divided we stand leveled + aghs = Aegis ceases to function upon death of meepo"
Video clip of the final test / display of the issue with Meepo in 12v12 is in url below.
https://vault.win-serv.com/PublicStorage/FASTDL-READ-ONLY/GeneralDotV2/ShareX/06-05-2021/generaldotv2_Sat06-05-2021%405-49-23.90.mp4

**Comment by lovro-m** [comment]
I cannot access the video, but I tested the steps stated and it seems like there is no problem with current aghs on meepo. Maybe this was when aghs spawned another meepo. The talent for 1 extra meepo also works fine.

**Comment by GeneralDotV2** [comment]
Updated video link below.
https://vault.win-serv.com/V/ShareX/2022/05/04/generaldotv2_Sat06-05-2021%405-49-23.90.mp4

**Comment by AustraliaIsMyCity** [comment]
no longer relevant since meepo's aghs was changed. tested with level 25 talent for a while and couldn't get it to break.
