### ISSUE TITLE
Perks not showing on scoreboard

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#271]
Probably not working in Overthrow either

Opened from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/852337833519087637)

**Comment by Sheodar** [comment]
Problem with recompile files. Need start game in tools mode before uploading @darklordabc

**Comment by Sheodar** [comment]
Fixed
