### ISSUE TITLE
smart random is not implemented on new server

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#275]
Opened from Discord by **Sanctus Animus#3413**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/853040015029960715)

**Comment by ArcadiaReduxAutomation** [comment]
Its an Overthrow 2.0 issue too

Comment from Discord by **darklord#1296**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/853041285861474334)

**Comment by SanctusAnimus** [comment]
Fixed
