### ISSUE TITLE
Fix wording of building repair perk

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#282]
Right now it says tower, where it should also include any building, primarily rax
![image](https://cdn.discordapp.com/attachments/501306949434867715/862326593824751636/unknown.png)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/862326594033811467)

**Comment by Draze22** [comment]
Fixed: https://github.com/arcadia-redux/12v12/commit/0270acba0de5e4cb74c5d7bb230247365085a62f.
