### ISSUE TITLE
Rebalance perks based on pick rates

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#283]
Buff the shittiest perks basically, maybe, maybe nerf the better ones, but mainly buff the shittiest ones

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/862328783817277481)

**Comment by ArcadiaReduxAutomation** [comment]
can I do this?

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/862328853028798474)

**Comment by Draze22** [comment]
Can someone link the stats page for 12v12 perks so I can get started on this?

**Comment by SanctusAnimus** [comment]
![image](https://user-images.githubusercontent.com/43399078/125572641-2be6d23b-4bc5-458e-b7bb-2e968da1142c.png)
it's a bit dead rn lmao

**Comment by Draze22** [comment]
Done.
