### ISSUE TITLE
Improve statistics page so you can filter by tiers

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#284]
The perk website stat page has the tiers all jumbled together, its a bit annoying, maybe add some kind of filter

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/862330356727676938)

**Comment by ArcadiaReduxAutomation** [comment]
make it sort by tiers by default, in 3 seperate tables next to each other

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/862331319522426881)

**Comment by SanctusAnimus** [comment]
Implemented
