### ISSUE TITLE
add family perk

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#285]
gives a random perk but of a higher tier, requires making a tier 4 perk class, for high level patrons that choose it, should have a shotgun as icon

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/862562029424082955)

**Comment by ArcadiaReduxAutomation** [comment]
![image](https://cdn.discordapp.com/attachments/501306949434867715/862563400592261140/unknown.png)

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/862563400780480512)

**Comment by ArcadiaReduxAutomation** [comment]
Instead give top tier, two random perks

Comment from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/862567169418461194)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/124868280-e024da00-e002-11eb-9075-873273e4dc5f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/124907853-fabf7900-e02b-11eb-8405-57277f6fcfa6.png)
