### ISSUE TITLE
Add extra button to vote dialogue, abuse of kick function

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#286]
Add a new button to the vote popup, so players can flag a certain vote initation as abuse of the kick function. When players get marked as abusing the vote function, we should record this value on the server, so we can track which players are abusing the function most

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/862611222776250388)

**Comment by Sheodar** [comment]
Added
