### ISSUE TITLE
Rewrite rearm so we can disable Traveller perks

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#293]
rearm

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/868320459215740948)

**Comment by AustraliaIsMyCity** [comment]
I mean it got the gist of it

**Comment by AustraliaIsMyCity** [comment]
rewrite rearm so we can disable traveller perk and innate perk

**Comment by AustraliaIsMyCity** [comment]
only applies to traveller perk now

**Comment by Sheodar** [comment]
Added
