### ISSUE TITLE
Finish Supporters/Developers Chatroom

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#294]
Its still missing a few features. For example, its look can probably be improved, there should be a checkbox that allows users to be anonymous when they post messages. We should always be able to see users names and steam profiles (regardless of if they use the checkbox, non supporters should be able to see the usernames of developers and users (unless they are anonymous) but the context of the chat should be blured so its unreadable (but the length of the message still discernible)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/868761887460954142)

**Comment by ArcadiaReduxAutomation** [comment]
> there should be a checkbox that allows users to be anonymous when they post messages.
this sounds like a really bad idea

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/868762036887244822)

**Comment by darklordabc** [comment]
It should also be renamed to Supporter/Developer chat, to show that developers are there.

**Comment by darklordabc** [comment]
Needs to also store messages of previous chats, preferably up to a year's worth of chat logs, so players can see the history of the conversation that has gone on.

**Comment by darklordabc** [comment]
Also prevent players from sending messages with no content 
![image](https://user-images.githubusercontent.com/16277198/126893686-bef9069c-3a1b-4a8f-9e09-9fd9ebe9369f.png)

**Comment by darklordabc** [comment]
- [ ] The game should only fetch first batch of messages when players open the chat window, it should have "Loading" for the delay.
- [ ] I guess it's okay for the game to fetch messages every 60 seconds after the first open, assuming players left a message and play and want to check for a reply, if this is the case, the chat window should have a red notification when there is an answer or a new reply, maybe a gold notification if a developer has replied. 
- [ ] Improve what non-supporters can see and do.
![image](https://user-images.githubusercontent.com/16277198/126915250-bf07afbd-0bc0-413b-8403-78b35541cf02.png)
I'd like non-supporters to be able to see the usernames and dates, and only the messages be blured
Also they should be able to scroll as well
Also can you allow non-supporters to type stuff, but when they click send button it takes them to the purchase screen
- [ ] Add some text for the anonymous mode feature
![image](https://user-images.githubusercontent.com/16277198/126915259-6b13f26d-8109-4115-be2f-220f91b385e2.png)

**Comment by darklordabc** [comment]
- [ ] Does not support long messages
![image](https://user-images.githubusercontent.com/16277198/127249753-0b020b74-746c-40f2-8bac-a016c940da29.png)

**Comment by darklordabc** [comment]
This would be better as "2 days ago"
![image](https://user-images.githubusercontent.com/16277198/127274393-15a91261-5f7e-43b3-b5eb-09a0e963d017.png)

**Comment by darklordabc** [comment]
- [ ]  Enable replies by us mentioning their steam id in our discord chat. They would see their nickname highlighted in our message

**Comment by darklordabc** [comment]
- [ ] Add sounds. When sending messages, when receiving, and in general UI sounds.
