### ISSUE TITLE
unidentified looping sound effect bug

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#295]
had multiple reports of random sounds, happening repetitively during a game

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/868992101369671720)

**Comment by GeneralDotV2** [comment]
I think during the update process on Steam for Dota 2, some files get wonky in certain updates at times. A simple fix for this is to verify the game files integrity within the Steam client.
