### ISSUE TITLE
Add mouse over tooltips for vote options

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#296]
For example, super towers doesnt say anything about how they are super, they could use some mouse over information
![image](https://cdn.discordapp.com/attachments/828460929427046430/868996643935117322/unknown.png)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/868996643968675901)

**Comment by Sheodar** [comment]
We had this. Fixed, now tooltips availeble again.
