### ISSUE TITLE
test theory that penalty bug is because of the name of the map

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#298]
a user suggested that the penalty bug may be because we have the same name as regular dota, seems doubtful, to test it just need to make a custom game with same leaver and penalty settings as 12v12 but with different map name and see if same bug exists.

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/869371317009395763)

**Comment by GeneralDotV2** [comment]
This does not work as I have just tested it with a full game of 24 players and a different map name while penalties were enabled.

**Comment by AustraliaIsMyCity** [comment]
Doesn’t work, even if local hosted in a 1 player lobby
