### ISSUE TITLE
Voting often ends before all players vote

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#302]
Every player needs to at least have a chance to report the report as abusive

**Comment by SanctusAnimus** [comment]
Well it can't stay forever on the side cause someone afk, right? And i believe it may end prematurely if there's already enough reports to claim vote as a critical failure. 
You should understand that we can't force all players to vote, or they'll just "press something so this annoying window go away"

**Comment by Draze22** [comment]
The main issue we need to fix is people instantly voting to get rid of someone, giving the rest of the players 2 seconds max to report the report as abusive. Just change it to expire after 10 seconds in cases like that.

**Comment by GeneralDotV2** [comment]
Isn't it already at like 30+ seconds to vote?

**Comment by Draze22** [comment]
> Isn't it already at like 30+ seconds to vote?
> https://github.com/arcadia-redux/12v12/blob/master/game/scripts/vscripts/common/voting_to_kick.lua#L8
> 40 seconds*

Once the player gets kicked the vote ends.
