### ISSUE TITLE
Non supporter players can still indefinitely avoid being kicked

### ISSUE THREAD

**Issue by GeneralDotV2** [arcadia-redux/12v12#303]
An issue with the kick system still persists. Where any player can avoid being kicked at any time by simple disconnecting during the vote kick stage and reconnecting right after. All someone has to do is troll to their hearts desire, and once they hear the noise of Chen ult, insta type disconnect into console and rejoin.. Then repeat.

**Comment by Sheodar** [comment]
Should be fixed now, reopen if error back.
