### ISSUE TITLE
Change end screen columns

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/12v12#304]
![image](https://media.discordapp.net/attachments/694501096604827648/871669195883024454/unknown.png?width=2496&height=1404)

Current:
- Hero
- Player name + level
- Team score
- KDA
- Items
- Current Gold
- MMR change
- GPM
- Total Damage Dealt
- Healing Dealt
- Networth
- Wards
- Killed enemies

Suggested:
- Hero
- Player name + level
- KDA
- Items
- Neutral Item
- Aghs blessing/aghs shard/moon shard
- Perk
- Networth
- GPM
- XPM
- Total Building Damage Dealt
- Total Hero Damage Dealt
- Total Damage Taken
- Healing Dealt
- Disable Duration Dealt (all root, hex, stun, sleep, silence, taunt, disarm, mute, slow, nightmare, feared duration, but not blind)
- Wards
- Camps stacked
- Killed enemies

Additionally:
- Show team score next to team name up the top left (eg. `THE RADIANT: 90`)
- Make MMR change visible somewhere but theres no need for its own column if its the same for everyone in the game
- Fix the bug where the enemy teams table has gaps in it through which you can see the game behind it

**Comment by Sheodar** [comment]
Didn't added Camps/Disable duration. Didn't see way for track it.
