### ISSUE TITLE
considering nerfing elder titan

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#310]
Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/873261317211967508)

**Comment by Draze22** [comment]
We have 2 main options for nerfing Elder Titan's Astral Spirit: 

1. Make it grant bonus damage and armor only for the first 5 enemy heroes it passes through. 
2. Reduce the amount of damage, armor and duration of magic immunity (aghs) granted by each hero passed through by 50%.
