### ISSUE TITLE
Nerf Mirana and Elder Titan

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#312]
Elder Titan:
Half his base damage per hero traveled through, dont change his talent
Change it so he gets 1 second per hero spell immunity not two

Mirana
Reduce duration to 13 seconds

Also update/add a tip to loading screen saying this nerf.

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/873433275396415539)

**Comment by Draze22** [comment]
Also reduce sentries recharge time from 60 seconds to 45 seconds.
