### ISSUE TITLE
Remove swap team mechanic

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#314]
1. It's buggy.
2. It can lead to teams becoming less balanced if low rated players leave one team and high rated players switch to their team.

**Comment by AustraliaIsMyCity** [comment]
+1

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/131956955-008eb926-1f3e-4fdb-a4e1-472c465010fe.png)

**Comment by Draze22** [comment]
Example or Swap Team mechanic ruining the game.

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/132302852-f3494e75-ff2a-41d8-a6cc-9d897cd14101.png)
