### ISSUE TITLE
allow instant purchase and transfer from secret shop

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#315]
When player's attempt to buy a secret shop item we teleport their courier there, get the loot, and teleport out, or some other solution

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/873785746048319538)

**Comment by ArcadiaReduxAutomation** [comment]
Other thing we could do is enable universal shop mode and block purchase of secret items for non supporters if they are not around secret shop, if teleporting turns out problematic

Comment from Discord by **Sanctus Animus#3413**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/873785934611636284)

**Comment by Draze22** [comment]
A third option is we make Couriers invulnerable, either for all player or just for supporters. Supporters would still have to send their courier to the secret shop to get items from it but they could leave it there without the enemy team killing it.

**Comment by AustraliaIsMyCity** [comment]
i dont think this should be added

**Comment by Sheodar** [comment]
Added https://github.com/arcadia-redux/12v12/pull/327
