### ISSUE TITLE
Neutral items dont drop to the hero, they drop where the creep died

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#318]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/873838275599675442)

**Comment by ArcadiaReduxAutomation** [comment]
just realised this is a valve bug when you queue a recipe only

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/873939259726377010)

**Comment by Draze22** [comment]
> just realised this is a valve bug when you queue a recipe only

What does that have to do with where Neutral Items drop?
