### ISSUE TITLE
Add scary warning about kick abuse to top 20 percent before issuing bans

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#322]
I think maybe we should add a big scaring notification to the top 20% players in report abuse data 'You are in the top 20% of players that have been reported as abusing the kick tool. You are in danger of losing your ability to vote kick entirely, if you don't improve your behaviour'

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/874600231092781108)

**Comment by Draze22** [comment]
The criteria for who gets warned may need to be changed based on what criteria we use to determine which players get their ability to vote kick removed.

**Comment by SanctusAnimus** [comment]
Tweaked:
- Have a fixed threshold for warning, and for ban. 
- Upon reaching lower bound of warning (say, 5 reports), each kick displays a warning about high report count and possibility of kick ban.
- Upon reaching higher bound of warning (say, 15 reports), player and all his party members can't kick until report count resets. 
- Error message should clearly indicate why, and be different for party members of kick abuser.
- Kick reports reset weekly.  

Should also reset current kick report stats before applying this as per-week threshold should be pretty low, and current reports leaderboard has 200+ reports per player.

**Comment by Sheodar** [comment]
Added. Difference messages for parties members/banned person/warning message.
