### ISSUE TITLE
Change linkens pendant to linkens shield

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#329]
Just acts as normal linkens, cant cast on anyone, isnt an item, has a graphic effect to indicate to enemies you have the perk, stats nerfed, apply to overthrow too

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876147349418831895)

**Comment by ArcadiaReduxAutomation** [comment]
code can be taken from https://github.com/arcadia-redux/custom_hero_clash/blob/master/game/scripts/vscripts/heroes/innates/linkens.lua

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876147401734357002)

**Comment by ArcadiaReduxAutomation** [comment]
i suggest 90/70/50/30 cooldown

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876147616092663879)

**Comment by ArcadiaReduxAutomation** [comment]
90/60/30/15

Comment from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876147797559226389)

**Comment by ArcadiaReduxAutomation** [comment]
The modifier buff icon should have a progress bar to show it recharging

Comment from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876147918858506261)

**Comment by Draze22** [comment]
This should pop after Linken's Sphere and QOP's Linken's talent.

**Comment by Snoresville** [comment]
should the cooldown be affected by cooldown reduction?

**Comment by Draze22** [comment]
> should the cooldown be affected by cooldown reduction?

For now no.

**Comment by Snoresville** [comment]
qop's talent seems to be reduced by cooldown reduction according to the wiki, you still sure?

**Comment by Draze22** [comment]
> qop's talent seems to be reduced by cooldown reduction according to the wiki, you still sure?

Yes.
