### ISSUE TITLE
Add descriptions to perks

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#332]
I dont actually know what this perk does, it would be nice to be able to know by mousing over, not the exact level or stats, but just what it generally does, apply to Overthrow too
![image](https://cdn.discordapp.com/attachments/501306949434867715/876386853094293564/unknown.png)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/876386853203370015)

**Comment by Draze22** [comment]
Ready for review: https://github.com/arcadia-redux/12v12/pull/337.

**Comment by darklordabc** [comment]
@Draze22 claim and close
