### ISSUE TITLE
Add vote option at start of game to hide MMR

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#341]
If vote succeeds the MMR of all players and the average MMR of team would be hidden too

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876581859834888192)

**Comment by Draze22** [comment]
It would make more sense to me to just give each player the option to hide mmr just for themself.

Alternatively we could have a vote option to make the game unranked or a separate unranked map.
