### ISSUE TITLE
you can buy more than 1 tome of knowledge every 10 minutes

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#343]
Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876848768908148736)

**Comment by Sheodar** [comment]
Need confirm @AustraliaIsMyCity

**Comment by AustraliaIsMyCity** [comment]
i can confirm

**Comment by AustraliaIsMyCity** [comment]
@Sheodar 
received many reports and seen it myself

**Comment by Sheodar** [comment]
Fixed
