### ISSUE TITLE
steel health perk (bonus x% hp) causes ice blast to deal way more damage than it should

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#346]
probably caused by the max health of the unit being constantly modified but since ice blast prevents healing it gets cut in half

Opened from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/876996983565471804)

**Comment by Sheodar** [comment]
Fixed for both mods
