### ISSUE TITLE
Add these to the list of abilities buffed by buff amplify

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#350]
Abilities that need to be added to the list:
- Dark Ascension.
- Exorcism.
- Heavenly Grace.

**Comment by Snoresville** [comment]
lmao, by technicality, nether strike's shard is already buffed because it reuses the black king bar modifier

**Comment by Draze22** [comment]
Updated the list.

**Comment by Draze22** [comment]
https://github.com/arcadia-redux/12v12/commit/454358299af6d1e621ffe94ab5ec41324f20b67b
