### ISSUE TITLE
Monkey King makes builder heal way more than it should (because of Wukong's)

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#357]
![image](https://user-images.githubusercontent.com/63279022/131201121-72e0de98-f43a-45ac-b48b-5aa9ff5726db.png)
![image](https://user-images.githubusercontent.com/63279022/131201114-a8d3ec91-1b67-4fdc-8b61-1867e23df687.png)

**Comment by Snoresville** [comment]
yikes
