### ISSUE TITLE
non secret shop items appear darkened in shop interface

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#365]
this is because the courier of of supporters is at the secret shop so it's only high lighting the secret shop items
![image](https://cdn.discordapp.com/attachments/828460929427046430/884509689637900329/unknown-90.png)

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/884509689885376542)

**Comment by Sheodar** [comment]
Attempt for fix it was pushed, need test it ingame (after recompile panorama)
