### ISSUE TITLE
ingame map-alt system doesnt work

### ISSUE THREAD

**Issue by riri323** [arcadia-redux/12v12#38]
in normal matches when u click ALT in the map and drag the cursor icons pop-up such as the red eye and green eye, etc, to warn the team that 'an enemy ward is here' or 'we need vision here'. This system doesnt appear in 12v12

**Comment by riri323** [comment]
this alt-feature appears if u hold alt in the minimap but this doesnt work if u hold alt in the real terrain

**Comment by darklordabc** [comment]
Yes, this does not work in any custom game I'm afraid.

**Comment by AustraliaIsMyCity** [comment]
@Sheodar can this be closed?

**Comment by Sheodar** [comment]
Added
