### ISSUE TITLE
12v12 Building's Health needs reworking

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#386]
At the moment We've made all towers very strong which prevents one team getting an advantage and snowballing to victory. This has been quite effective however It could use some tweaking.

In Vanilla Dota:

Tier 1 towers: 1800hp
Tier 2 towers: 2500hp
Tier 3 towers: 2500hp
Tier 4 towers: 2600hp
Ranged rax: 1300hp
Melee rax: 2200hp
Ancient: 4500hp

12v12 Currently:

Tier 1 towers: 4800hp
Tier 2 towers: 4900hp
Tier 3 towers: 5000hp
Tier 4 towers: 5100hp
Ranged rax: 1300hp
Melee rax: 2200hp
Ancient: 4500hp

I propose we simply double the hp of all major buildings (compared to Vanilla Dota):

Tier 1 towers: 3600hp
Tier 2 towers: 5000hp
Tier 3 towers: 5000hp
Tier 4 towers: 5200hp
Ranged rax: 2600hp
Melee rax: 4400hp
Ancient: 9000hp

The proposed changes barely alter the hp of tier 2-4 towers but make tier 1 towers easier to take (currently it takes far too long to take tier 1 towers in most 12v12 games). It also makes it much harder to take Barracks and the Ancient which currently take very little effort to kill and most teams lose after their Tier 3 towers start falling.

**Comment by Sheodar** [comment]
Implemented (that's have little config now, easy for edit in future)
