### ISSUE TITLE
Reconsider the nerfs to Bloodseeker and Chaos Knight

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#387]
We've nerfed 6 heroes in 12v12. 4 of them (Zeus, Mirana, Elder Titan and Silencer) are in the top 10 winrates and should obviously stay nerfed however Bloodseeker and Chaos Knight (the other 2 nerfed heroes) both have under 50% winrates.

I understand that Chaos Knight was nerfed because everyone hated it and it was pretty laggy too and I can imagine that at some point Bloodseekers were probably running around at 3k movespeed in 12v12 games and that's why he was nerfed. However we have data showing us exactly how good every hero is on average and it doesn't make much sense for Bloodseeker and Chaos Knight to be nerfed to below 50% winrates while heroes like Spectre that have a 58% winrate (highest in game) aren't nerfed.

**Comment by darklordabc** [comment]
I greenlight removing the nerfs to these two heros.

**Comment by Draze22** [comment]
I've implemented partial buffs to both heroes. If they're still weak and not being complained about I'll buff them back to vanilla values.
