### ISSUE TITLE
the day/night cycle is fucked

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#391]
first day starts at 12:30

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/888575760690970634)

**Comment by ArcadiaReduxAutomation** [comment]
![image](https://cdn.discordapp.com/attachments/828460929427046430/888581980801867876/unknown.png)

Comment from Discord by **Australia Is My City#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/888581981452009533)

**Comment by Sheodar** [comment]
Fixed
