### ISSUE TITLE
Make sure all lane creep mechanics are working as intended

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/12v12#396]
Lane creeps spawn the first time as the game timer reaches 00:00, right after the game horn sounds. After that, they spawn every 30 seconds. Unlike melee and ranged creeps, siege creeps start spawning on the eleventh wave, and then every tenth wave. This means siege creeps spawn every 5 minutes, with the first ones spawning at 5:00.

Initially, a creep wave consists of 3 melee creeps and 1 ranged creep (and 1 siege creep every 10th wave). As the game progresses, their quantity gets upgraded:

31st wave and onwards (15:00): All lanes get +1 melee creep. Total count of melee creeps is now 4 for all lanes.
61st wave and onwards (30:00): All lanes get +1 melee creep. Total count of melee creeps is now 5 for all lanes.
71st wave and onwards (35:00): All lanes get +1 siege creep. Total count of siege creeps is now 2 for all lanes.
81st wave and onwards (40:00): All lanes get +1 ranged creep. Total count of ranged creeps is now 2 for all lanes.
91st wave and onwards (45:00): All lanes get +1 melee creep. Total count of melee creeps is now 6 for all lanes.
After the 45th minute, a creep wave consists of 6 melee creeps and 2 ranged creeps (and 2 siege creeps every 10th wave), resulting in a total of 8 (10 with siege creeps) creeps per wave.

Every 7 minutes 30 seconds, melee and ranged creeps gain a permanent upgrade to their health and attack damage, as well as an increase to their bounties. The following bonuses are applied:

Melee creeps: +12 health, +1 attack damage, +1 gold bounty
Ranged creeps: +12 health, +2 attack damage, +6 gold bounty, +8 experience bounty
Super melee creeps: +19 health, +2 attack damage, +1.5 gold bounty
Super ranged creeps: +18 health, +3 attack damage, +6 gold bounty
Mega melee creeps: +1.5 gold bounty
Mega ranged creeps: +6 gold bounty
These health and damage upgrades are applied a maximum of 30 times, while the gold and experience bounty upgrades have no limit. This means their health and damage are fully upgraded at 225:00 in-game time, which is 3 hours and 45 minutes. The total values on each upgrade cycle can be seen in the following table.

Siege creeps only gain one upgrade, and that is +16 damage upon destroying their respective lane's ranged barracks.

**Comment by AustraliaIsMyCity** [comment]
https://dota2.fandom.com/wiki/Lane_creeps

**Comment by Draze22** [comment]
XP, HP and Damage scale the same as in regular Dota (with XP being double). Gold does not, it seems to increase over time.

**Comment by AustraliaIsMyCity** [comment]
Thanks @Draze22

**Comment by AustraliaIsMyCity** [comment]
@Draze22 Can you do the same for neutral gold/xp bounties (including stacking mechanics)

**Comment by Draze22** [comment]
> @Draze22 Can you do the same for neutral gold/xp bounties (including stacking mechanics)

Camps: XP is exactly doubled, gold gain starts the same as regular Dota and increases over time (same as everything else).

Stacked Camps: XP is almost exactly doubled, gold for the player killing the camp seems to be correct. Haven't checked the gold for the stacker but since the XP/gold for the player killing the camp was changed more recently it's unlikely the gold for the stacker is different in 12v12.

**Comment by Draze22** [comment]
XP from outposts is also doubled btw.
