### ISSUE TITLE
If a player does not collect a neutral item, after 6 seconds, it should automatically trigger the take vote mechanic

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#410]
Players can troll by just not collecting the neutral items, if they do this, the item should be offered to other players to collect as usual, and then teleported to stash if nobody wants it

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/894129724916400158)

**Comment by fcalife** [comment]
After the 6 seconds elapse, move the item to the player's inventory and start the vote. Vote normally.

If their inventory is full, move the item to the team's neutral stash.
