### ISSUE TITLE
When you drop a neutral items onto ground, it should instantly teleport to stash (apply to Overthrow too)

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#412]
Prevent trolling and giving neutral items to enemies, like how we prevent players from dropping wards

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/894133739880349696)

**Comment by fcalife** [comment]
Only applies to when players intentionally drop neutrals to the ground **from their inventory**
