### ISSUE TITLE
suggestion: scores at the end of the game

### ISSUE THREAD

**Issue by riri323** [arcadia-redux/12v12#43]
at the end of each game can we have an MVP or a 1st, 2nd, 3rd place in both the winning and losing teams. This could be based  on the performance in the game or the values in damage dealt, damage taken, assists, kills, death, etc.  idk. just a suggestion, i think this would make the scoreboard more intersting and the endgame fun. Thank you.

**Comment by GeneralDotV2** [comment]
The problem with that is global ult heroes would next to always be the MVP due to the fact that a heavy majority of games they do the most damage and get the most kills.

**Comment by riri323** [comment]
1. not really..almost every game these heroes are banned. they get used very rarely.

2. usually the good players get the highest damages and scores at the end and they dont even use global heroes. just regular heroes but played with good skills.

3. like in many of the games even supports get the highest damage values and outscore the carries

4. idk. i think it will be a nice addition to the game and makes us wanna do well and in the end get in the top 3 or so.

Thank you so much for this game...(cant 'comment', just 'close and comment')

**Comment by riri323** [comment]
reopen,,,sorry,,, i couldnt comment
