### ISSUE TITLE
Hero Auras don't work on illusions

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#444]
This makes it way too easy for enemies to tell which is the real illusion.

**Comment by Sheodar** [comment]
@Draze22, can u give more details? Because some auras works fine. Maybe several auras doesn't work?
![image](https://user-images.githubusercontent.com/23509297/139585043-8d237432-3740-4d53-a5bb-8dd459c13a5d.png)

**Comment by Draze22** [comment]
> @Draze22, can u give more details? Because some auras works fine. Maybe several auras doesn't work? ![image](https://user-images.githubusercontent.com/23509297/139585043-8d237432-3740-4d53-a5bb-8dd459c13a5d.png)

Ah, the cosmetic auras, not buff/debuff auras.

**Comment by Sheodar** [comment]
Understand. Okie, will fix it.
