### ISSUE TITLE
Update chatwheel to include Marci voice lines, and any other voice things that may not have been added

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#448]
Chat wheel hasnt been updated for a while, its probably missing some variants of sounds that the real dota one has, also its missing Marci. Need to add Marci and other misc ones if there are some, this update needs to apply to all the games that use the chat wheel, which at least includes Overthrow, CHC and maybe Pathfinder

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/890461846753140767/903514649356541992)

**Comment by Sheodar** [comment]
Added for 12v12/OT/CHC.
