### ISSUE TITLE
Griefing At Start of Match

### ISSUE THREAD

**Issue by AnonymousPerson12345** [arcadia-redux/12v12#452]
Just played a game and during the beginning disconnect, someone on our team took control of each hero and spent their skill points in stats. On some, he also bought all clarities and chugged them all to waste gold. Not cool.

**Comment by Draze22** [comment]
Sheodar is currently working on a way to prevent players from doing this.

**Comment by AnonymousPerson12345** [comment]
Cool, thanks!
