### ISSUE TITLE
Create a blacklist of players that can never be immune to kicking

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#454]
Manually maintained, but controlled by server, so we dont have to upload a new version everytime, when there is evidence of a player griefing, or even just multiple reports, the supporter will lose kick immunity but maintain all the other perks

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/908967300365950986)

**Comment by ArcadiaReduxAutomation** [comment]
Supporters who have lost this privilege, should have an item or some message to them that they have lost their kick immunity due to reports of griefing, they should contact the  chat to talk to developers to discuss this loss of privileges if they think it was unfair.

Comment from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/908967849165488144)

**Comment by ArcadiaReduxAutomation** [comment]
there's also this thing about being able to add perks to other accounts which could be just another account for the blacklisted player so maybe devs should consider blacklisting both the main account and the other accounts the blacklisted player added perks to

Comment from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/909345022648913941)

**Comment by Draze22** [comment]
No longer relevant since we're making Supporters able to be kicked.
