### ISSUE TITLE
reversed numerical labels 

### ISSUE THREAD

**Issue by mr-tallnut** [arcadia-redux/12v12#467]
was trying 12 v 12 dota and faced a problem where the numbers on buffs/debuffs numbers are side ways

**Comment by Draze22** [comment]
> was trying 12 v 12 dota and faced a problem where the numbers on buffs/debuffs numbers are side ways

Do you used the reversed minimap?

**Comment by mr-tallnut** [comment]
I didn't change anything in the game setting.
