### ISSUE TITLE
End Screen is broken

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#468]
Happened because of the last update.

![image](https://user-images.githubusercontent.com/63279022/145788306-04375a30-23e8-4ef6-8505-5f77b2b92071.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/145796860-4d3f3285-6303-4894-82e0-c034cee151d7.png)

**Comment by ZLOY5** [comment]
Fixed by @Sheodar
