### ISSUE TITLE
Mmr changes display incorrectly in the post game screen

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#475]
The same mmr change should be shown for each player on the same team for starters.

![image](https://user-images.githubusercontent.com/63279022/148159932-7306cf91-2409-4d3a-b228-ad7a6f48388a.png)

**Comment by ZLOY5** [comment]
Can you explain more about this, not sure i understand

**Comment by Draze22** [comment]
Afaik all players on the same team gain/lose the same amount of mmr for winning/losing. Clearly if that's true the post game screen incorrectly displays how much mmr players gained/lost.

**Comment by Draze22** [comment]
MMR change shown in the end game scoreboard (Clinkz):

![image](https://user-images.githubusercontent.com/63279022/149293468-979c47d0-7db2-4f5f-a9e0-6775f1b8bb8e.png)

Actual MMR change:

![image](https://user-images.githubusercontent.com/63279022/149293597-3c7cc59f-006e-4e63-af06-383859b2da86.png)
