### ISSUE TITLE
Players can leave the game during the loading phase without punishment

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#476]
![image](https://user-images.githubusercontent.com/63279022/148632279-3fcd97ce-148d-4c03-812b-9d9154c47aaa.png)

**Comment by GeneralDotV2** [comment]
This is done by simply locking and unlocking the lobby before it fills. Not much to it really.

**Comment by Draze22** [comment]
> This is done by simply locking and unlocking the lobby before it fills. Not much to it really.

There's nothing we'd be able to do about it then right?
