### ISSUE TITLE
Neutral items get lost after rejoining the game after getting disconnected

### ISSUE THREAD

**Issue by lebrice** [arcadia-redux/12v12#486]
When I get DCed (which happens often), when I get back, and pick up a Neutral item, it gets lost! (Can't get it from the neutral items tab, and get no option to keep or send it back to neutral tab)

**Comment by Draze22** [comment]
So once you disconnect from the game you can no longer pick up or use any neutral items?

**Comment by lebrice** [comment]
@Draze22 Yes exactly. Also, just FYI, when reconnecting to the game, the "perks" window is empty, and the perk icon on the left is the same "+" as at the start of the game. 
This visual bug is my queue to not try to pick up any of the neutral items, otherwise they are lost, and nobody can claim them.

Can you reopen this please? Issue is still ongoing.

**Comment by Draze22** [comment]
I don't understand how this bug would happen since every player disconnects at the start of the game.

**Comment by Draze22** [comment]
@lebrice how low did you disconnect for?

**Comment by Draze22** [comment]
I tested this by disconnecting 4 times total, for long enough to abandon and I was still had no issues with neutral items.

**Comment by lebrice** [comment]
I don't disconnect voluntarily: The client freezes (the characters are running in-place) for a while, and then I get disconnected.
When I do, I rejoin immediately.
