### ISSUE TITLE
Weak Team buff sometimes gets applied to the team with higher mmr

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#493]
Most likely commit to have caused this (although I don't understand how): https://github.com/arcadia-redux/12v12/commit/d70ea8c5e531f6819ddd207e9a96dff485e6aade.

**Comment by ZLOY5** [comment]
I'm not sure this fixed, because found only a few places that POTENTIALLY lead to this bug, and can't reproduce this in tools
