### ISSUE TITLE
Halve the xp granted by weak team buff

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#494]
The main complaint about the weak team buff is the potential for it to help the lower mmr team snowball through being higher level.

**Comment by ZLOY5** [comment]
https://github.com/arcadia-redux/12v12/commit/d70ea8c5e531f6819ddd207e9a96dff485e6aade
One more time?

**Comment by ZLOY5** [comment]
Also amybe you forgot to change `MAX_BONUS` too
