### ISSUE TITLE
Supporters can't sell items they bought while dead, while they're dead

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#496]
Only an issue in 12v12 and not OT2.0

**Comment by ZLOY5** [comment]
Any additional info? Can't reproduce

**Comment by Draze22** [comment]
1. Have perks.
2. Die.
3. Buy an item while dead.
4. You won't be able to sell the item bought until they respawn.

They should be able to sell items while still dead as long as they bought the item while dead.
