### ISSUE TITLE
Background for the checkout page breaks in ultrawide

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#497]
![image](https://user-images.githubusercontent.com/63279022/153738408-6bff049e-680a-4a99-913f-85e37db080b4.png)

![image](https://user-images.githubusercontent.com/63279022/153738412-ca5071ef-0f9f-4c9b-844e-3911e074f47d.png)

**Comment by SanctusAnimus** [comment]
Fixed, server will be updated to reflect changes later
