### ISSUE TITLE
Allow Supporters to be kicked from games

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#499]
**Once this is ready to be implemented, notify Draze22 _before_ it's implemented**

Currently it takes 60% of players voting to kick someone for the vote kick to go through.

Make Tier 1 supporters kickable by a 70% vote and Tier 2 supporters kickable by an 80% vote.

**Comment by crash0r** [comment]
If this comes, nobody will buy perk then.

**Comment by iamsiberian** [comment]
> If this comes, nobody will buy perk then.
I didn't record videos, but very often in my games Tier 1 & Tier 2 supporters deliberately ruined games

**Comment by AustraliaIsMyCity** [comment]
@Draze22 why am i assigned this when there is an open PR implementing this?

**Comment by Draze22** [comment]
> @Draze22 why am i assigned this when there is an open PR implementing this?

@AustraliaIsMyCity sorry, didn't see it.

**Comment by crash0r** [comment]
> > If this comes, nobody will buy perk then.
> 
> I didn't record videos, but very often in my games Tier 1 & Tier 2 supporters deliberately ruined games

Well most game ruiners dont have a perk and with the new change of 60% ppl required to kick somebody, nearly NO eligible kicks got through. The new 60% votekick requirement is not suitable for 12v12. It just doesnt work. Many are too lazy to vote even if the player to be kicked is really trolling or ruining the game...

**Comment by Draze22** [comment]
We changed it because people were getting kicked despite not griefing because their team wanted the game to be safe to leave.

**Comment by crash0r** [comment]
> We changed it because people were getting kicked despite not griefing because their team wanted the game to be safe to leave.

Didnt see ANY of those kicks of people who got kicked while not griefing nor are games actually safe to leave if somebody got kicked...
