### ISSUE TITLE
Detection Patch

### ISSUE THREAD

**Issue by vjt4** [arcadia-redux/12v12#514]
Is there any interest in a detection patch? Previously sentries cost half they did in vanilla but Valve cut the price of sentries. Perhaps 12v12 could get reduced to 25.

Currently late game is just absurdly annoying with everyone having a Silver Edge and sentries running out of stock.

Also, would people be interested in a consumable item (like Moonshard) for ~8,000 gold that provides hero true sight in a small area? If so ill work on it and submit a pull request

**Comment by Draze22** [comment]
I doubt reducing the cost of sentries would make much of a difference and definitely wouldn't solve there not being enough sentries late game. 

We don't want to add custom items to 12v12 so a consumable gem doesn't work for us either.

I do however think some other improvements could be made to detection in 12v12. Faster sentry restock time could help, although I suspect it will mostly just lead to more sentries getting killed and neither team really having better detection. What's really needed is for Valve to add a detection slot so 6 slotted players can still carry dust.
