### ISSUE TITLE
Blessing Amp missing a few abilities. Aghs shard time should be lowered. 

### ISSUE THREAD

**Issue by vjt4** [arcadia-redux/12v12#515]
Aghs shard time got lowered from 20 minutes to 15 minutes in vanilla. 
12v12 timing should be lowered from 15-->11?

New Slark Aghs Shard, Night Stalker Dark Ascension and Omni Heavenly Grace do not get extended by blessing amplify.

**Comment by Draze22** [comment]
Duplicate of #350.
