### ISSUE TITLE
Game crashes when someone uses a voiceline

### ISSUE THREAD

**Issue by lebrice** [arcadia-redux/12v12#522]
Title. Happening now, no one can get a game going in US-East

**Comment by Draze22** [comment]
This seems to apply to Overthrow 2.0 too.

**Comment by ArtofNature** [comment]
yep

**Comment by otakutyrant** [comment]
Is voiceline the chat wheel? I play Dota 2 in China and have encounted game crash for three times. Somenone says because of a bug related to chat wheel.

**Comment by Draze22** [comment]
chess, using the chatwheel crashes the game, we have a temporary fix ready and will upload it soon.

**Comment by prekel** [comment]
Update it uploaded, but bug is still here

**Comment by prekel** [comment]
20 sec ago
![image](https://user-images.githubusercontent.com/19646569/160125158-14c9d2cb-498c-47dd-8789-589fbd31e235.png)

**Comment by otakutyrant** [comment]
> 20 sec ago ![image](https://user-images.githubusercontent.com/19646569/160125158-14c9d2cb-498c-47dd-8789-589fbd31e235.png)

The same situation too.

**Comment by iamsiberian** [comment]
https://github.com/arcadia-redux/12v12/issues/524
