### ISSUE TITLE
Reduce the max number of Tombstone Zombies

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#534]
It lags the game a lot when there a multiple Tombstones, each creating the max number of Zombies.

**Comment by Draze22** [comment]
Unfortunately Tombstone max zombies seems to be hard coded so this will require rewriting Tombstone.

**Comment by ZLOY5** [comment]
@Draze22 is this still relevant? I can copy ability from OT3 and make it work like vanilla, but with lower zombie max count

**Comment by Draze22** [comment]
Sure, make it work the same way as OT3 with 32 max zombies.

**Comment by Draze22** [comment]
@ZLOY5

**Comment by AustraliaIsMyCity** [comment]
Isnt there a server cvar for this tho?
