### ISSUE TITLE
Consumed Aghs Scepter isn't counted towards networth in the end game screen

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#544]
Might also not count Aghs Shard.

**Comment by GeneralDotV2** [comment]
Maths

![chrome_8MHcivHG2S](https://user-images.githubusercontent.com/5668755/163592065-3941c0d9-0b23-4afc-8901-441d2245b96b.png)

https://cdn.discordapp.com/attachments/694501096604827648/964536130777280522/unknown.png
