### ISSUE TITLE
Veno 40+ Armor

### ISSUE THREAD

**Issue by Tarrock1** [arcadia-redux/12v12#547]
I've noticed this constantly, but Venos are finding a way to get over 40 armor at the start of the game giving them ~80% resistance. I think it has something to do with the armor perk as I've noticed every veno with this issue has the perk.

https://imgur.com/8Vyy7K7

**Comment by Draze22** [comment]
They're a high supporter who chose family and got the armor perk. It's not a bug, the armor perk just gives a lot of physical resistance.
