### ISSUE TITLE
Extra gold for low winrate heroes is inconsistent 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#553]
I played 2 games today as Underlord, the first game I got roughly 220 extra gold, the second game I got no extra gold.

**Comment by GeneralDotV2** [comment]
After you win a game as a hero that gets, you gain no bonus gold for a set number of matches after the win. I don't remember the exact number on top of my head.

**Comment by SanctusAnimus** [comment]
Yes, that's intentional
