### ISSUE TITLE
seriousness bug,i can't see myself

### ISSUE THREAD

**Issue by butterfly2012** [arcadia-redux/12v12#554]
after entering the game, i can't choose myself.
![image](https://user-images.githubusercontent.com/37859775/165103314-c591b231-c2ed-41d3-89e8-894b5f58c580.png)
![image](https://user-images.githubusercontent.com/37859775/165103598-1775fcd1-697e-45a6-bb96-b613f28eeb72.png)

**Comment by Draze22** [comment]
Did you take a long time to reconnect to the game?
