### ISSUE TITLE
Change how stats for perks are displayed

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#556]
Show family perk stats as their own line instead of combining them with the stats of the perk that was randomed.

This needs to be done for 12v12 and OT2.

**Comment by Draze22** [comment]
@SanctusAnimus do you need more information to do this or have you just been too busy/not gotten around to this yet?

**Comment by SanctusAnimus** [comment]
iirc it's not sent as family perk from lua, because there's no family perk per-se, it's just giving random other perk
might be worth to ask sheodar to check this

**Comment by Draze22** [comment]
@Sheodar can you help with this?
