### ISSUE TITLE
Create a blacklist of players that are banned from 12v12/OT2/OT3 games

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#558]
Needs to be discussed and tested thoroughly.

- [ ] Manually maintained list that preferably doesn't require updating the game to modify.
- [ ] They can join games, but can't control their hero, buy items, chat, ping, use scan/fortify, etc. They should random their hero once the picking phase is over (at 0s, just before they start losing gold).
- [ ] Give them a message in the centre of their screen explaining that they've been banned for their behaviour in 12v12/OT2/OT3 games.
- [ ] The list should apply to 12v12, OT2 and OT3.

**Comment by tobarcn** [comment]
see this hack
https://www.bilibili.com/video/BV1Xr4y1x7at/

**Comment by Draze22** [comment]
Clearly Scripting, what's their Steam ID?

**Comment by crash0r** [comment]
> Needs to be discussed and tested thoroughly.
> 
> * [ ]  Manually maintained list that preferably doesn't require updating the game to modify.
> * [ ]  They can join games, but can't control their hero, buy items, chat, ping, use scan/fortify, etc. They should random their hero once the picking phase is over (at 0s, just before they start losing gold).
> * [ ]  Give them a message in the centre of their screen explaining that they've been banned for their behaviour in 12v12/OT2/OT3 games.
> * [ ]  The list should apply to 12v12, OT2 and OT3.

Most stupid enhancement I ever saw. You tend to ruin the whole idea od 12v12 you know?

**Comment by SanctusAnimus** [comment]
Punishment setting is implemented, exact consequences should be discussed and implemented separately per-tier

**Comment by crash0r** [comment]
> Punishment setting is implemented, exact consequences should be discussed and implemented separately per-tier

Which punishment?
