### ISSUE TITLE
tomes can still be bought from shop

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#566]
Opened from Discord by **Luminance#9760**
Follow the conversation [here](https://discord.com/channels/501306949434867713/890461846753140767/972687945003839568)

**Comment by AustraliaIsMyCity** [comment]
![Uploading 94645510-44DE-465D-9B04-07470CCEDE53.jpeg…]()

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/167279414-0ad925a8-07b6-4b99-bcbf-7012a99c6ea7.png)

**Comment by AustraliaIsMyCity** [comment]
turns out someone forgot to upload the game when they added this to the patch notes...
