### ISSUE TITLE
Get 12v12 backend server ready for an mmr reset on July 1st

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/12v12#577]
Instead of resetting everyone to 1500 which will make matchmaking kinda garbage for a while, make the post reset mmr scale based on pre reset mmr:
0-1000 -> 1000
1001-2000-> 1500
2001-3000 -> 2000
3001-4000-> 2500
4001+ -> 3000

Save the Steam ID's and MMR of the top 100 players pre reset, we will hopefully use them later.
For now no rewards will be given, we should have an internal discussion regarding this at some point before reset.
Schedule the next mmr reset for January 1st 2023 (with the same rules, may revisit later).

**Comment by SanctusAnimus** [comment]
reset happened
