### ISSUE TITLE
Quite a few crash/disconnect reports after the most recent update

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#581]
![image](https://user-images.githubusercontent.com/63279022/171656585-14537537-bdc8-436a-8854-a4df413f207a.png)

![image](https://user-images.githubusercontent.com/63279022/171656666-df47b462-a59c-4bfa-983d-e33d11a7d3a9.png)

![image](https://user-images.githubusercontent.com/63279022/171656714-c6c1c5ba-caa2-4b06-8d9a-20684a4068cb.png)

**Comment by Draze22** [comment]
This update to be specific:

![image](https://user-images.githubusercontent.com/63279022/171657104-56c41046-e536-4d01-84a6-44527b01c7cb.png)

**Comment by crash0r** [comment]
Constant crashes on reconnecting. Up to 5-6 times in a row...

**Comment by ZLOY5** [comment]
Any additional info?
You just get into main menu or game completely crashes?
Maybe someone can give console logs

**Comment by Draze22** [comment]
From what I've exerienced the Dota client completely crashes.

**Comment by crash0r** [comment]
At the moment it is not occurring anymore
