### ISSUE TITLE
Nerf the 56%+ winrate heroes

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#591]
The goal is to get these heroes to have 54-55% winrates.

Spectre (59% winrate) options:

- Decrease Haunt's duration
- Increase Haunt's cooldown
- Modify Haunt to only cast on up to 6 enemy heroes

Mirana (57% winrate) options:

- Further decrease Moonlight Shadow's duration
- Increase Moonlight Shadow's fade delay
- Increase Moonlight Shadow's cooldown

Nature's Prophet (57% winrate) options:

- Increase Teleportation's cooldown (including the talent)
- Increase Wraith of Nature's cooldown
- Decrease Wrath of Nature's max targets
- Decrease Wrath of Nature's added damage per bounce and Scepter max root duration
- Buff backdoor protection (not 100% sure this would nerf NP)

Venomancer (56% winrate):

- Decrease the number of Shard plague wards per hero from 2 --> 1 (pretty sure this is the best option since it also has the benefit of reducing lag)

**Comment by Snoresville** [comment]
are those winrates across all maps?

**Comment by Snoresville** [comment]
oh nvm i thought this was ot3

**Comment by vjt4** [comment]
Desolate doesn't scale with amount of players and in fact is generally worse with more units on the map. 

Really she should follow in ET's footsteps and have 25% reduced haunt illusion damage and duration.

**Comment by zizhengwu** [comment]
The following is the heroes winrate **pre** nerf I got from the discord server. Is there an updated heroes winrate sheet since the nerf has been in effect for 2 months now?

![unknown](https://user-images.githubusercontent.com/2246655/185633995-b88693bd-4563-4cee-961d-9035d16caad6.png)
