### ISSUE TITLE
Lobby bot

### ISSUE THREAD

**Issue by crs0718** [arcadia-redux/12v12#593]
There is a player called "付费等待" who should be a bot in US east / west servers. He keeps entering the DOTA2 12V12 game lobby and failed to load the game again and again just intends to waste everybody's two minutes. The host cannot kick him out because the bot re-join back no matter how fast the host kicks him. This is suuuuuuper annoying. Many players report to Value but they did nothing. This guy may create another steam ID once in a while. By any chance to help to ban this player? Many of my friends quit playing 12v12 due to this reason. It has been more than two months.

![image](https://user-images.githubusercontent.com/29806295/175195133-3190e012-def4-45a4-aced-02ecbd65c951.png)

**Comment by Draze22** [comment]
You can report the account to Valve but we can't do anything to stop players or bots from trolling lobbies.
