### ISSUE TITLE
hi  i pay 5$ pay now but no mmr reset is 3time 

### ISSUE THREAD

**Issue by mickeyusername** [arcadia-redux/12v12#602]
i want reset and I would like to request a refund for the 2time 10$
my id 337179731

**Comment by SanctusAnimus** [comment]
Please provide screenshot of an email from Stripe of payment made

**Comment by SanctusAnimus** [comment]
According to my information you have been successfully reset to 1500 mmr, multiple times
It may appear in next game

**Comment by mickeyusername** [comment]
no i trying to reset and check 10 time still 2k

**Comment by mickeyusername** [comment]
oh now 1.5k reset but i trash my 10~15$

**Comment by SanctusAnimus** [comment]
Naming inconsistency, sorry, internally free tier is tier 0, and highest tier is tier 2. 
What i meant is additional month of highest tier.

**Comment by mickeyusername** [comment]
ok give me 2month 2 tier ty

**Comment by SanctusAnimus** [comment]
Added, will take effect from next game. Thanks for your commitment to our game
