### ISSUE TITLE
[BUG] Weak team bug

### ISSUE THREAD

**Issue by shinchan299** [arcadia-redux/12v12#605]
The higher MMR team will get the weak team buff. 

PS. I think if there is sponsors in the game., please test it when you release the new version. Actually, every time a new version released, there will be many bugs.  It's confused.

**Comment by AustraliaIsMyCity** [comment]
Thanks for the report, I also found another bug while fixing this one;
Weak team buff was sometimes applying regardless of if the mmr gap was higher than the threshold

Fixed by: https://github.com/arcadia-redux/12v12/commit/5a767fe9f6bd0ff2669c75eb1462701f8040dace
