### ISSUE TITLE
Players who revive by any means get fountain invulnerability

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#618]
Aegis, Wraith King's Reincarnation and Undying's reincarnation talent all work.

![image](https://user-images.githubusercontent.com/63279022/180592398-900696a1-1f8f-4a16-b1f2-c324cb3f27fc.png)

**Comment by ZLOY5** [comment]
Should invuln be applied if hero reincarnate on own fountain?

**Comment by Draze22** [comment]
> Should invuln be applied if hero reincarnate on own fountain?

No, It should only be applied from respawning after a normal death.

**Comment by Draze22** [comment]
This is very abusable and needs to be fixed ASAP.
