### ISSUE TITLE
F12 screenshot function not working

### ISSUE THREAD

**Issue by crs0718** [arcadia-redux/12v12#632]
F12 screenshot function not working, was working before.

**Comment by GeneralDotV2** [comment]
You need to check that setting in your Steam settings as this has nothing to do with 12v12, or even Dota 2 at all
![steam_jy1H6tu8Yp](https://user-images.githubusercontent.com/5668755/184787227-7e5d1270-a748-4733-8ee9-d02ad603ab3a.png)
.
