### ISSUE TITLE
Can't use ''kick troll" on invulnerable afk hero

### ISSUE THREAD

**Issue by Ruimbento** [arcadia-redux/12v12#644]
We can't kick Pango. He stole out tome of knowledge and kept 8k money
![image](https://user-images.githubusercontent.com/16365331/188107416-6f1f76d1-5fb3-4341-aeef-8f9056a040c0.png)
![image](https://user-images.githubusercontent.com/16365331/188106973-79023ed4-99d1-4ee0-86a5-181913fc5b74.png)

**Comment by AustraliaIsMyCity** [comment]
wont be fixed since this way of kicking people is being removed
