### ISSUE TITLE
Buff Amplify perks don't work when buffs are refreshed on a hero

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#653]
For example if an Omniknight uses Guardian Angel (with Scepter) with +30% buff duration it will last 10+3 = 13 seconds, however if he then refreshes Guardian Angel and casts it again before the first one ends, its duration will be reset to 10 seconds instead of 13 seconds.

**Comment by ZLOY5** [comment]
@Draze22 impossible to do, except if we rewrite perk to override special values(like CHC Torture Pipe)

**Comment by Draze22** [comment]
> @Draze22 impossible to do, except if we rewrite perk to override special values(like CHC Torture Pipe)

Is there any issue with doing that?

**Comment by ZLOY5** [comment]
Only issue it is a bunch of  work (need to check each ability in game), but it also should fix bugs like #546 and #545

**Comment by Draze22** [comment]
Closed #546 and #545, and added the delayed label so we can ignore this while we focus on more important things.

**Comment by AustraliaIsMyCity** [comment]
fixed
