### ISSUE TITLE
Update Sentry Cost and Restock time to be 50% of vanilla again.

### ISSUE THREAD

**Issue by vjt4** [arcadia-redux/12v12#666]

**Comment by Draze22** [comment]
I don't see this as necessary, the map is the same size as in vanilla Dota, with the same number of Observers to deward. Also Dust's cost and cooldown are decreased to help against invis heroes.

**Comment by vjt4** [comment]
Currently the overrides have never been updated even though sentries have changed half a dozen time since then.

**Comment by Sheodar** [comment]
There is not description about "50% of dota". It is already have reduced stock time (45sec) and it is enough
