### ISSUE TITLE
scoreboard improvements

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/12v12#674]
Add column titles to gold and kick.
![image](https://user-images.githubusercontent.com/50186248/193386746-41c61887-6ce4-4748-8916-eae099698c68.png)
Replace kick icon with a red shoe (see above example)
Add a column title to disable help, but since that wont fit make it ⓘ, which shows a tooltip which reads `disable help` when hovered over.
Hovering over the kick icon should show a tooltip which reads `Starts a vote to kick this player. The vote will go through if %vote_kick_pct_for_this_player%%% of votes are in favour.\nPlease note that parties' votes count as 1.`

**Comment by Draze22** [comment]
I agree with everything except the new kick icon.
